/**
 * Mock project data for previewing the ProjectCard component
 * with Arabic content.
 */
export const MOCK_PROJECTS = [
  {
    _id: "mock-project-1",
    title: "منصة التجارة الإلكترونية للأزياء",
    shortDescription:
      "منصة تجارة إلكترونية متكاملة مع نظام إدارة المخزون وبوابة دفع آمنة ولوحة تحكم تحليلية شاملة.",
    clientName: "أزياء العصر",
    projectType: "web-app",
    industry: "ecommerce",
    status: "completed",
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe", "AWS"],
    budgetMin: 3000,
    budgetMax: 5000,
    currency: "USD",
    duration: { value: 6, unit: "months" },
    teamSize: "medium",
    publishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 210 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
  },
  {
    _id: "mock-project-2",
    title: "تطبيق إدارة المواعيد الطبية",
    shortDescription:
      "تطبيق موبايل لحجز المواعيد الطبية مع نظام إشعارات وتذكيرات ودفع إلكتروني وإدارة السجلات الطبية.",
    clientName: "مستشفى النور",
    projectType: "mobile-app",
    industry: "healthcare",
    status: "completed",
    technologies: ["React Native", "Firebase", "Node.js", "MongoDB"],
    budgetMin: 2200,
    budgetMax: 3800,
    currency: "USD",
    duration: { value: 4, unit: "months" },
    teamSize: "small",
    publishedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
  },
  {
    _id: "mock-project-3",
    title: "نظام إدارة المحتوى التعليمي",
    shortDescription:
      "منصة تعليمية تفاعلية مع إدارة الدورات والطلاب والمدرسين ونظام اختبارات وشهادات.",
    clientName: "أكاديمية المستقبل",
    projectType: "web-app",
    industry: "education",
    status: "ongoing",
    technologies: ["Next.js", "Python", "Django", "MySQL", "Redis"],
    budgetMin: 4500,
    budgetMax: 8000,
    currency: "USD",
    duration: { value: 8, unit: "months" },
    teamSize: "large",
    publishedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-4",
    title: "تطبيق إدارة الاستثمارات العقارية",
    shortDescription:
      "تطبيق موبايل لإدارة الاستثمارات العقارية مع متابعة العوائد والمصروفات وإدارة المستندات.",
    clientName: "مجموعة العقارات المتحدة",
    projectType: "mobile-app",
    industry: "real-estate",
    status: "completed",
    technologies: ["Flutter", "Dart", "Laravel", "MySQL"],
    budgetMin: 2800,
    budgetMax: 4200,
    currency: "USD",
    duration: { value: 5, unit: "months" },
    teamSize: "medium",
    publishedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 195 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-5",
    title: "لوحة تحليلات البيانات المالية",
    shortDescription:
      "لوحة تحكم تحليلية متقدمة مع تصورات بيانية تفاعلية لتحليل البيانات المالية والتنبؤ بالاتجاهات.",
    clientName: "بنك الأمان",
    projectType: "data-science",
    industry: "finance",
    status: "completed",
    technologies: ["Python", "Pandas", "Plotly", "FastAPI", "Docker"],
    budgetMin: 1800,
    budgetMax: 3000,
    currency: "USD",
    duration: { value: 3, unit: "months" },
    teamSize: "small",
    publishedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 110 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-6",
    title: "نظام إدارة الموارد البشرية SaaS",
    shortDescription:
      "منصة سحابية متكاملة لإدارة الموارد البشرية مع الحضور والانصراف والرواتب والإجازات والتقييمات.",
    clientName: "هيومن كابيتال",
    projectType: "web-app",
    industry: "saas",
    status: "ongoing",
    technologies: ["Vue.js", "Go", "PostgreSQL", "Kubernetes", "Terraform"],
    budgetMin: 7000,
    budgetMax: 12000,
    currency: "USD",
    duration: { value: 12, unit: "months" },
    teamSize: "large",
    publishedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 240 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
  },
  {
    _id: "mock-project-7",
    title: "هوية بصرية ونظام تصميم",
    shortDescription:
      "تصميم هوية بصرية متكاملة ونظام تصميم شامل مع مكتبة مكونات UI وأنماط العلامة التجارية.",
    clientName: "شركة الإبداع الرقمي",
    projectType: "design",
    industry: "saas",
    status: "completed",
    technologies: ["Figma", "Adobe XD", "Illustrator", "Storybook"],
    budgetMin: 900,
    budgetMax: 1500,
    currency: "USD",
    duration: { value: 2, unit: "months" },
    teamSize: "solo",
    publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-8",
    title: "استشارات بنية تحتية سحابية",
    shortDescription:
      "تقديم استشارات فنية وتطوير بنية تحتية سحابية على AWS مع إعداد DevOps pipeline متقدم.",
    clientName: "تك سوليوشنز",
    projectType: "consulting",
    industry: "saas",
    status: "completed",
    technologies: ["AWS", "Terraform", "Docker", "Jenkins", "ELK Stack"],
    budgetMin: 2500,
    budgetMax: 4500,
    currency: "USD",
    duration: { value: 4, unit: "months" },
    teamSize: "small",
    publishedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-9",
    title: "منصة البث المباشر للترفيه",
    shortDescription:
      "منصة بث مباشر للمحتوى الترفيهي مع نظام اشتراكات ودفع ومحادثات مباشرة وتفاعل جمهور.",
    clientName: "إنترتين ميديا",
    projectType: "web-app",
    industry: "entertainment",
    status: "archived",
    technologies: ["WebRTC", "Socket.io", "React", "Node.js", "Redis"],
    budgetMin: 5200,
    budgetMax: 9000,
    currency: "USD",
    duration: { value: 7, unit: "months" },
    teamSize: "large",
    publishedAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 580 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    _id: "mock-project-10",
    title: "تطبيق مواقيت الصلاة والأذكار",
    shortDescription:
      "تطبيق موبايل بسيط لعرض أوقات الصلاة والقبلة والأذكار اليومية مع إشعارات وتصميم أنيق.",
    clientName: "مؤسسة النور",
    projectType: "mobile-app",
    industry: "education",
    status: "completed",
    technologies: ["React Native", "Expo", "AsyncStorage"],
    budgetMin: 700,
    budgetMax: 1200,
    currency: "USD",
    duration: { value: 1, unit: "months" },
    teamSize: "solo",
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
];
