export const MOCK_POSITION_CARDS = [
  {
    id: "mock-position-1",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
  {
    id: "mock-position-2",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
  {
    id: "mock-position-3",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
  {
    id: "mock-position-4",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
  {
    id: "mock-position-5",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
  {
    id: "mock-position-6",
    title: "مصمم جرافيك",
    location: "الرياض، السعودية",
    salary: "10520$ سنوياً",
    workType: "دوام كامل",
    level: "مستوى متقدم",
    description:
      "انضم لفريقنا كمصمم منتجات أول وشاركنا في تطوير حلول مبتكرة لتعزيز تجربة المستخدم ونمو المشاريع.",
    applications: 32,
    views: 40,
    daysRemaining: 12,
    timelineProgress: 64,
    status: "open",
    logoText: "PS",
    tags: ["التصميم", "تجربة المستخدم", "مستوى متقدم"],
  },
];
