export const freelancerProjectsMock = [
  {
    id: "project-1",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "active",
    budget: "$5,000",
    startDate: "2026-04-14",
    totalDays: 12,
    deliveredAt: null,
  },
  {
    id: "project-2",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "completed",
    budget: "$5,000",
    startDate: "2026-04-01",
    totalDays: 10,
    deliveredAt: "2026-04-11",
  },
  {
    id: "project-3",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "completed",
    budget: "$5,000",
    startDate: "2026-03-28",
    totalDays: 14,
    deliveredAt: "2026-04-11",
  },
  {
    id: "project-4",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "active",
    budget: "$5,000",
    startDate: "2026-04-15",
    totalDays: 12,
    deliveredAt: null,
  },
  {
    id: "project-5",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "active",
    budget: "$5,000",
    startDate: "2026-04-15",
    totalDays: 12,
    deliveredAt: null,
  },
  {
    id: "project-6",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "active",
    budget: "$5,000",
    startDate: "2026-04-15",
    totalDays: 12,
    deliveredAt: null,
  },
  {
    id: "project-7",
    title: "تطوير موقع تجارة إلكترونية",
    clientName: "شركة تقنية بلس",
    status: "active",
    budget: "$5,000",
    startDate: "2026-04-15",
    totalDays: 12,
    deliveredAt: null,
  },
];
